#!/usr/bin/env python3
import os
import stat
from os import chmod
from os.path import abspath, join, basename, expanduser
from shutil import copyfile
from sys import argv

source_script = abspath(argv[1])
name = basename(source_script)
if name.endswith(".py"):
    name = name[:-3]
name = name.replace('_', '-')
target_script = join(expanduser('~'), 'bin', name)
copyfile(source_script, target_script)
st = os.stat(target_script)
chmod(target_script, st.st_mode | stat.S_IEXEC)
