#!/usr/bin/env python3
import os
import stat
from os import chmod, symlink
from os.path import abspath, join, basename, expanduser
from sys import argv

script = abspath(argv[1])
name = basename(script)
if name.endswith(".py"):
    name = name[:-3]
st = os.stat(script)
chmod(script, st.st_mode | stat.S_IEXEC)
symlink(script, join(expanduser('~'), 'bin', name))
